# Ciência de dados
É uma disciplina multidisciplinar que envolve a coleta, análise e interpretação de grandes conjuntos de dados para obter insights e tomar decisões informadas. Combina elementos da **estatística, matemática, programação, e conhecimento de negócios**.

## Scikit-learn (sklearn)
Biblioteca de código aberto que oferece uma ampla gama de ferramentas e algoritmos para **aprendizado de máquina, mineração de dados e análise estatística**. Ele é construído em cima de outras bibliotecas populares como NumPy, SciPy e matplotlib. Suas funcionalidades são:
- **Pré-processamento de dados** 
- **Algoritmos de aprendizado de máquina** 
- **Avaliação de modelos**
- **Validação de modelos**

In [2]:
import pandas as pd
# definindo df
df = pd.DataFrame({'x': [14, 33, 42, 54, 62, 71],
                'y': [1, 3, 4, 5, 6, 4]})

df

    x  y
0  14  1
1  33  3
2  42  4
3  54  5
4  62  6
5  71  4

In [4]:
# pré-processamento
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['x'] = scaler.fit_transform(df[['x']])
df

          x  y
0 -1.688895  1
1 -0.686114  3
2 -0.211112  4
3  0.422224  5
4  0.844448  6
5  1.319450  4

In [9]:
from sklearn.linear_model import LinearRegression

df = pd.DataFrame({'x': [14, 33, 42, 54, 62, 71],
                'y': [1, 3, 4, 5, 6, 4]})

# modelagem / treinamento de um modelo de regressão
modelo = LinearRegression()

# treinando o modelo 
# x é a informação e y é a variavel resposta (preço no exemplo da aula)
modelo.fit(df[['x']], df[['y']])

# fazendo previsões
df['LigReg'] = modelo.predict(df[['x']])
df

    x  y    LigReg
0  14  1  1.619777
1  33  3  2.934076
2  42  4  3.556639
3  54  5  4.386722
4  62  6  4.940111
5  71  4  5.562674

## Feature engineering
é o processo de criação e transformação de variáveis (ou características) nos dados brutos para melhorar o desempenho dos modelos de aprendizado de máquina. 
- Seleção de características
- Criação de novas características
- Transformação de características
- Tratamento de valores ausentes

Dependendo do tipo de dados que trabalhamos podemos criar diferentes tipos de visões das variáveis
- Temporais - criar janelas, como por ex, maior saldo do cliente nos últimos 3 meses
- Categóricas - geralmente precisam ser convertidas em um formato numérico antes de serem usadas em modelos de aprendizado de máquina
- Relacionais - relacionando 2 variáveis como por ex, razão dos usos sobre o limite do cartão de crédito.